name: Rectify11

on:
  workflow_dispatch:
  push:
  pull_request:
  workflow_run:
    workflows: ["Submodules Sync"]
    types:
      - completed

jobs:
  build:
    runs-on: windows-latest
    env:
      NUGET_CERT_REVOCATION_MODE: offline
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.6
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: recursive
        lfs: true

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: "8"

    - name: Restore NuGet Packages
      run: nuget restore Rectify11Installer.sln

    - name: Build
      run: msbuild Rectify11Installer.sln /p:Configuration=Release /p:platform=x64

    - name: Publish
      run: dotnet publish Rectify11Installer -c Release -p:PublishProfile=FolderProfile -property:SolutionDir=${{ github.workspace }}\
      
    - name: Upload Rectify11Installer
      uses: actions/upload-artifact@v4.3.3
      with:
        name: Rectify11Installer (x64)
        path: Rectify11Installer\bin\Release\net8.0-windows\publish\win-x64\Rectify11Installer.exe
        compression-level: 0
